# -*- mode: ruby -*-
# vim: set ft=ruby :
ansible_user = "ans"
# work
ssh_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEbrduEvsWILqNr45wV05HTX+4nMVwcr5CkQUtMbTcII"
# home
#ssh_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOvcTcrFTzhPvVAh9rjhQPH41UIFojMnZxYSD8tvJDer vagrant@ansible"


MACHINES = {
  :ansible => {
    :box_name => "bento/ubuntu-22.04",
    :ip_addr => '192.168.10.99',
    :ssh_port => 2099
  },
  :app0 => {
    :box_name => "bento/ubuntu-22.04",
    :ip_addr => '192.168.10.11',
    :ssh_port => 2011
  },
  :app1 => {
    :box_name => "bento/ubuntu-22.04",
    :ip_addr => '192.168.10.21',
    :ssh_port => 2021
  },
  :app2 => {
    :box_name => "bento/ubuntu-22.04",
    :ip_addr => '192.168.10.22',
    :ssh_port => 2022
  },
  :db1 => {
    :box_name => "bento/ubuntu-22.04",
    :ip_addr => '192.168.10.31',
    :ssh_port => 2031
  },
  :db2 => {
    :box_name => "bento/ubuntu-22.04",
    :ip_addr => '192.168.10.32',
    :ssh_port => 2032
  },  
  :mon => {
    :box_name => "bento/ubuntu-22.04",
    :ip_addr => '192.168.10.40',
    :ssh_port => 2040
  },  
  :xxx => {   ### Болванчик
    :box_name => "bento/ubuntu-22.04",
    :ip_addr => '192.168.10.50',
    :ssh_port => 2050
  },  
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|
          box.vm.box_check_update = false  # Отключение проверки обновлений
          box.vm.box = boxconfig[:box_name]
          box.vm.hostname = boxname.to_s
          config.vm.synced_folder ".", "/vagrant", disabled: false # пробрасывать каталог
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.network "forwarded_port", guest: 22, host: boxconfig[:ssh_port]
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "560"]
          end

          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
            # Добавление пользователя ansible_user и размещение его public ssh-key
            useradd -m -s /bin/bash "#{ansible_user}"
            mkdir -p /home/"#{ansible_user}"/.ssh
            chmod 755 /home/"#{ansible_user}"/.ssh
            touch /home/"#{ansible_user}"/.ssh/authorized_keys
            chmod 644 /home/"#{ansible_user}"/.ssh/authorized_keys
            echo "#{ssh_key}" > /home/"#{ansible_user}"/.ssh/authorized_keys
            chown -R "#{ansible_user}":"#{ansible_user}" /home/"#{ansible_user}"/.ssh
            # Добавление пользователя ansible_user в группу sudoers
            usermod -aG sudo "#{ansible_user}"
            echo "#{ansible_user} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/"#{ansible_user}"
            SHELL

          case boxname.to_s
          when "app1", "app2", "xxx"  # Проброс каталога для WEB
            box.vm.synced_folder "d:\\nextcloud.files\\", "/data/nextcloud", 
              owner: "www-data", group: "www-data", 
              mount_options: ["dmode=770", "fmode=770"],
              disabled: false
          end
      end  
  end
end
