- name: 'Enable service MariaDB'
  service:
    name: mariadb
    state: started
    enabled: yes

# -----------------------------------------------------------------------------

# Читаем статус Master-а. Master вернет параметры, другие - ничего
- name: Get MariaDB master state
  community.mysql.mysql_info:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    filter: master_status
  register: db_master_status

- debug:
    msg: "{{ db_server_id }} - {{ db_master_status.master_status }}"
  when: db_debug|default(False) == True

# # Если это мастер, но параметры не выдает то делаем reset для binlog    ❓ Этот шаг будет всегда пропускаться?
# - name: "(Master) Reset binlog"
#   command: '/usr/bin/mysql -u root -e "RESET MASTER"'
#   when: db_server_id == 1 and db_master_status.master_status == {}

# Читаем статус Slave-а. Если репликация настроена, то вернет Slave_IO_Running: Yes, иначе - No
- name: "(Slave) Get status"
  community.mysql.mysql_replication:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: getslave
  register: db_slave_status


- debug:
    var: db_slave_status.Slave_IO_Running
  when: db_debug|default(False) == True

# Настройка репликации для Slave если репликации еще нет.
- name: "(Slave) Setup replication"
  command: '/usr/bin/mysql -u root -e "CHANGE MASTER TO master_host=\"{{ master_host }}\", master_user=\"{{ dbuser_replicator }}\", master_password=\"{{ dbuser_replicator_pass }}\", master_use_gtid=current_pos"'
  when: db_server_id != 1 and db_slave_status.Slave_IO_Running|default("No") == "No"
  notify: 'Restart MariaDB Service'

# - debug:
#     msg: "master_host= {{ master_host }}"
#   when: db_debug|default(False) == True

# Запуск репликации для Slave если репликации еще нет.
- name: "(Slave) Start slave"
  community.mysql.mysql_replication:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: startslave
  when: db_server_id != 1 and db_slave_status.Slave_IO_Running|default("No") == "No"
