# Установка Apache и необходимых пакетов
- name: Install sofware packages for APP 
  apt:
    name:
     - apache2 
     - libapache2-mod-php 
     - php-gd 
     - php-mysql 
     - php-curl 
     - php-mbstring 
     - php-intl 
     - php-gmp 
     - php-bcmath 
     - php-xml 
     - php-imagick 
     - php-zip
    state: present

- name: Ensure directory exists
  ansible.builtin.file:
    path: "{{ nc_data_files }}"
    state: directory
    mode: '0755'    

# # Распаковка файловой части Nextcloud
# - name: Unpack the archive into the destination directory
#   ansible.builtin.unarchive:
#     src: "{{ remote_archive_path }}"
#     dest: "{{ nc_data_files }}"
#     # extra_opts:
#     #   - '--exclude=*.txt' # Пример исключения всех .txt файлов, подходит для tar, по умолчанию ничего исключать не нужно
#     # remote_src: true

# Настройка конфигурации
- name: Copy Nextcloud config for Apache
  template:
    src: apache_nextcloud.conf.j2
    dest: /etc/apache2/sites-available/nextcloud.conf
    owner: root
    group: root
    mode: '0644'
  notify:  
    - Reload Apache

- name: Copy Nextcloud config.php
  template:
    src: config.php.j2
    dest: /opt/nextcloud_config.php
    owner: www-data
    group: www-data
    mode: '0770'
  notify:  
    - Reload Apache    

- name: Create a symbolic link to a file config.php 
  file:
    src: /opt/nextcloud_config.php
    dest: "{{ nc_data_files }}/nextcloud/config/config.php"
    state: link     

# Включение необходимых модулей
- name: Enable Apache rewrite module
  command: a2enmod rewrite

- name: Enable Apache headers module
  command: a2enmod headers

- name: Enable Apache env module
  command: a2enmod env

- name: Enable Apache dir module
  command: a2enmod dir

- name: Enable Apache mime module
  command: a2enmod mime    

 

# Activate config Nextcloud
- name: Enable Nextcloud site config
  command: 
    cmd: a2ensite nextcloud.conf
  notify:  
    - Reload Apache

