server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://{{ hostvars['mon']['ansible_host'] }}:3100/loki/api/v1/push

scrape_configs:
- job_name: auth-log
  static_configs:
  - targets:
      - localhost
    labels:
      job: node/auth
      __path__: /var/log/auth.log
      nodename: "{{ inventory_hostname }}"
  pipeline_stages:
    - match:
        selector: '{job="node/auth"}'
        stages:
          - regex:
              expression: '^(?P<datetime>\w+ \d{2} \d{2}:\d{2}:\d{2}) (?P<user>\w+) (?P<process>.*): (?P<message>.*)$'
          - labels:
              datetime:
              user:
              process:
#             pid:
              message:

- job_name: nginx
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginxlogs
      __path__: /var/log/nginx/*log
      nodename: "{{ inventory_hostname }}"      
  pipeline_stages:
    - match:
        selector: '{job="nginxlogs"}'
        stages:
        - regex:
            expression: '^(?P<remote_addr>[\w\.]+) - (?P<remote_user>[^ ]*) \[(?P<time_local>.*)\] "(?P<method>[^ ]*) (?P<request>[^ ]*) (?P<protocol>[^ ]*)" (?P<status>[\d]+) (?P<body_bytes_sent>[\d]+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"?'
        - labels:
            remote_addr:
            remote_user:
            time_local:
            method:
            request:
            protocol:
            status:
            body_bytes_sent:
            http_referer:
            http_user_agent:
