server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://{{ hostvars['mon']['ansible_host'] }}:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: authlogs
      __path__: /var/log/auth.log
      node_name: "{{ ansible_hostname }}"
      # node_ip: "{{ ansible_host }}"
  pipeline_stages:
    - regex:
        expression:
          ^(?P<datetime>\w+ \d{2} \d{2}:\d{2}:\d{2}) (?P<user>\w+) (?P<process>.)\[(?P<pid>\d+)\]: (?P<message>.)$
 