- name: Install packages
  apt:
    name:
      - libaio1
      - python3-pip
      - mariadb-server
    state: present

- name: Make sure mysql module is installed
  pip:
    name: pymysql

  # mysql_secure_installation
- name: Delete Hostname based MySQL user
  mysql_user: 
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: root 
    host: "{{ansible_nodename}}" 
    state: absent

- name: Create MySQL User for DEBUG
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "debug"
    host: "%"
    password: "debug"
    state: present

- name: Grant Privileges for DEBUG MySQL User
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "debug"
    host: "%"
    priv: '*.*:ALL'
    state: present    

- name: Create MySQL User for Nextcloud
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ mysql_nextcloud_user }}"
    host: localhost
    password: "{{ mysql_nextcloud_pass }}"
    state: present

- name: Create Nextcloud Database
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: nextcloud
    state: present
    collation: utf8mb4_general_ci
    encoding: utf8mb4  

# - name: Grant Privileges to MySQL User on Nextcloud Database
#   community.mysql.mysql_user:
#     login_unix_socket: /var/run/mysqld/mysqld.sock
#     name: "{{ mysql_nextcloud_user }}"
#     #host: "{{ app_ip }}"
#     host: "['192.168.10.21', '192.168.10.22']"
#     priv: 'nextcloud.*:ALL'
#     state: present

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False        
  
- name: Copy config
  template:
    src: 50-server.cnf
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf 

- name: Initialize mariadb
  service:
    name: mariadb
    state: restarted
