---
## This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: all
  become: true
  gather_facts: yes
  vars_files:   
    - ./vars.yml
  roles:
    - provision
    - monitoring-node
  tags:
  - provision

# Base configure database servers.
- hosts: db
  become: true
  vars_files:
    - ./vars.yml
  roles:
    - provision-db
  tags:
  - provision-db

# Configure replication DB Master-Slave  
# - hosts: db
#   become: true
#   vars_files:
#     - ./vars.yml
#   roles:
#     - replicate-db-old
#   tags:
#   - replicate-db-old

# ALT Configure MariaDB Master-Slave Replication  
# - hosts: db
#   become: true
#   vars_files:
#     - ./vars.yml
#   roles:
#     - replicate-db
#   tags:
#   - replicate-db

# Настройка мастер-слейв репликации в MariaDB
- hosts: db
  become: true
#  db_debug: true
  vars_files:
    - ./vars.yml
  roles: 
    - replicate-db
  # tasks:
  #   - name: Проверка настроенной репликации или наличия базы данных nextcloud в Master DB
  #     shell: >
  #       echo "SHOW SLAVE STATUS\G" | mysql -u {{ db_admin }} -p{{ db_admin_pass }} -h {{ master_host }} | grep Slave_IO_State
  #     register: replication
  #     ignore_errors: true
  #     changed_when: false

  #   # - name: Поиск базы данных nextcloud в Master DB
  #   #   shell: >
  #   #     echo "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'nextcloud'" |
  #   #     mysql -u {{ db_admin }} -p{{ db_admin_pass }} -h {{ master_host }}
  #   #   register: nextcloud
  #   #   ignore_errors: true
  #   #   changed_when: false

  #   - name: Check if Nextcloud Database exists
  #     community.mysql.mysql_db:
  #       login_unix_socket: /var/run/mysqld/mysqld.sock
  #       name: "{{ nc_database }}"
  #       state: present
  #     register: nc_db_check
  #     tags: debug

  #   - name: Replication on/off
  #     include_role:
  #       name: replicate-db
  #     when: replication.rc = 'false' and nc_db_check.rc = 'false'
  tags:
  - replicate-db

# Database NEXTCLOUD
- hosts: db_main
  become: true
  vars_files:
    - ./vars.yml
  roles:
    - nextcloud-db
  tags:
  - nextcloud-db

# Configure application hosts
- hosts: app
  become: true
  vars_files:
    - ./vars.yml
  roles:
    - app
  tags:
  - app

# Cofigure Front
- hosts: front
  become: true
  vars_files:
    - ./vars.yml
  roles:
    - front
  tags:
  - front

# Cofigure Monitor (Loki+Grafana)
- hosts: mon
  become: true
  vars_files:
    - ./vars.yml
  roles:
    - monitoring
  tags:
  - monitoring

# Configure periodical create sql-dumps
- hosts: db_slave
  become: true
  vars_files:
    - ./vars.yml
  roles:
    - backup
  tags:
  - backup