# Первичная инициализация хостов, установка пакетов
- hosts: all
  gather_facts: true
  become: true
  vars_files:
    - ./vars.yml
  roles:
    - provision

# Стнадартное разворачивание MySQL на db-хостах
- hosts: db
  gather_facts: true
  become: true
  vars_files:
    - ./vars.yml
  roles:
     - { role: mysql_ini, tags: mysql_ini_tag }

# - hosts: db_main
#   gather_facts: true
#   become: true
#   vars_files:
#     - ./vars.yml
#   roles:
#      - { role: mysql_main, tags: mysql_main_tag }