become: true
ansible_ssh_user: ans
ansible_ssh_private_key_file: /home/vagrant/.ssh/id_ed25519
# Подавление запроса fingeprint
ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

# Nextcloud vars
nextcloud_url: https://download.nextcloud.com/server/releases/latest.zip
mysql_nextcloud_user: nextcloud #database user
mysql_nextcloud_password: testpassword #database password