---
- hosts: all
  gather_facts: true
  become: true

  tasks:
        - name: install soft
          apt:
            name:
                - nano
                - traceroute
                - nmap
                - iptables
            state: present
            update_cache: true
        
                
        - name: install nginx on centralServer
          apt:
            name:
                - nginx
            state: present
          when: (ansible_hostname == "centralServer")  

        - name: set up forward packages across routers
          sysctl:
            name: net.ipv4.conf.all.forwarding
            value: '1'
            state: present

        - name: disable default route
          template: 
            src: 00-installer-config.yaml
            dest: /etc/netplan/00-installer-config.yaml
            owner: root
            group: root
            mode: 0644
            when: (ansible_hostname != "inetRouter") or 
                (ansible_hostname != "inetRouter2")

        - name: add routes
          template: 
              src: "50-vagrant_{{ansible_hostname}}.yaml"
              dest: /etc/netplan/50-vagrant.yaml
              owner: root
              group: root
              mode: 0644
      
        - name: Restart network
          systemd:
            state: restarted
            name: network      