---
# Handler to handle DB tier notifications

- name: Restart MariaDB Service
  service:
    name: mariadb
    state: restarted
    enabled: yes

- name: flush priveleges
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False   