---
# This role will install MySQL and create db user and give permissions.
- name: Install MariaDB packages
  apt:
    name:
      - libaio1
      - python3-pip
      - mariadb-server
    state: present

- name: Make sure mysql module is installed
  pip:
    name: pymysql

- name: Change MySQL bind address
  replace:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: 'bind-address\s*=\s*127.0.0.1'
    replace: 'bind-address = 0.0.0.0'
  notify: Restart MariaDB Service

- name: Delete Hostname based MySQL user
  community.mysql.mysql_user: 
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: root 
    host: "{{ansible_nodename}}" 
    state: absent
  notify:
  - flush priveleges

- name: Create MySQL Admin User for Debug
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    user: "{{ db_admin }}"
    password: "{{ db_admin_pass }}"
    host: "{{ item }}"
    priv: '*.*:ALL,GRANT'
    state: present
  loop: "{{ db_admin_access_hosts }}"
  notify:
  - flush priveleges

# - name: Initialize mariadb
#   service:
#     name: mariadb
#     state: restarted

# ------------------------------------------------------------------------
# Создание пользователя для репликации на Master
- name: Create replication user {{ dbuser_replicator }} on Master
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ dbuser_replicator }}"
    password: "{{ dbuser_replicator_pass }}"
    host: "{{ item }}"
    priv: '*.*:REPLICATION SLAVE'
    state: present
  loop: "{{ replication_host }}"
  when: db_server_id == 1
  notify: flush priveleges

# Копируем config файл для Master c включеным binlog
- name: Copy config Master Server with Enable binlog
  template:
    src: 50-server-master.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
  when: db_server_id == 1
  notify: Restart MariaDB Service         # 🔴

# Установка server-id для Slave
- name: "Config: Set server-id for Slave"
  lineinfile:
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: "^ *#* *server-id"
    line: "server-id = {{ db_server_id }}"
    # backup: yes
  when: db_server_id != 1
  notify: Restart MariaDB Service  

# # Применяем конфигурацию
# - name: Restart MariaDB Service
#   service:
#     name: mariadb
#     state: restarted
#     enabled: yes  

#-----------------------------------------------
