---
# This role will install MySQL and create db user and give permissions.
- name: Install MariaDB packages
  apt:
    name:
      - libaio1
      - python3-pip
      - mariadb-server
    state: present

- name: Make sure mysql module is installed
  pip:
    name: pymysql

- name: Change MySQL bind address
  replace:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: 'bind-address\s*=\s*127.0.0.1'
    replace: 'bind-address = 0.0.0.0'
  notify: Restart MariaDB Service

- name: Delete Hostname based MySQL user
  community.mysql.mysql_user: 
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: root 
    host: "{{ansible_nodename}}" 
    state: absent
  notify:
  - flush priveleges

- name: Create MySQL Admin User
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    user: "{{ db_admin }}"
    password: "{{ db_admin_pass }}"
    host: "{{ item }}"
    priv: '*.*:ALL,GRANT'
    state: present
  loop: "{{ db_admin_access_hosts }}"
  notify:
  - flush priveleges

- name: Initialize mariadb
  service:
    name: mariadb
    state: restarted

