- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Load Nginx config
  template:
    src: nginx.conf.j2
    dest: '{{ front_nginx_config_file }}'
  notify:
    - restart nginx  


- name: Create symbolic link in sites-enabled
  file:
    src: '{{ front_nginx_config_file }}'
    dest: /etc/nginx/sites-enabled/{{ nc_url}}
    state: link
  notify:
    - restart nginx    