# -*- mode: ruby -*-
# vim: set ft=ruby :

ssh_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE6DjTuZGIABfSBXc23bBBmRdBKd56QzHqqn5u2kwdUE"
ansible_user = "ans"

MACHINES = {
  :ansible => {
    :box_name => "bento/ubuntu-22.04",
    :ip_addr => '192.168.10.250'
  },
  :app1 => {
    :box_name => "bento/ubuntu-22.04",
    :ip_addr => '192.168.10.21'
  },
  :db1 => {
    :box_name => "bento/ubuntu-22.04",
    :ip_addr => '192.168.10.31'
  },
  :db2 => {
    :box_name => "bento/ubuntu-22.04",
    :ip_addr => '192.168.10.32'
  },  
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|
          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          config.vm.synced_folder ".", "/vagrant", disabled: false # Не пробрасывать каталог
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "560"]
          end

          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
            # Добавление пользователя ansible_user и размещение его public ssh-key
            useradd -m -s /bin/bash "#{ansible_user}"
            mkdir -p /home/"#{ansible_user}"/.ssh
            chmod 755 /home/"#{ansible_user}"/.ssh
            touch /home/"#{ansible_user}"/.ssh/authorized_keys
            chmod 644 /home/"#{ansible_user}"/.ssh/authorized_keys
            echo "#{ssh_key}" > /home/"#{ansible_user}"/.ssh/authorized_keys
            chown -R "#{ansible_user}":"#{ansible_user}" /home/"#{ansible_user}"/.ssh
            # Добавление пользователя ansible_user в группу sudoers
            usermod -aG sudo "#{ansible_user}"
            echo "#{ansible_user} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/"#{ansible_user}"
            SHELL
          
          case boxname.to_s
            when "ansible"
              box.vm.synced_folder "d:\\OTUS\\PROJECT\\ansible\\", "/ansible", disabled: false
              box.vm.provision "shell", inline: <<-SHELL
              sudo cp /ansible/key/id_ed25519 /home/vagrant/.ssh/ && 
              sudo chown vagrant:vagrant /home/vagrant/.ssh/id_ed25519 && 
              sudo chmod 600 /home/vagrant/.ssh/id_ed25519 
              sudo apt-get update -y &&                            
              sudo apt-get install python3 ansible -y
                SHELL

            # when "db1"
            #   box.vm.provision "shell", inline: <<-SHELL
            #   # Установка модуля Ansible для MySQL
            #   #sudo apt-get update -y
            #   #sudo apt-get install python3-pip -y && pip install PyMySQL
            #     SHELL
          end
      end  
  end
end
