# become: true
# gather_facts: true

ansible_ssh_user: ans
ansible_ssh_private_key_file: /home/vagrant/.ssh/id_ed25519

# Подавление запроса fingeprint
ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
