ansible_ssh_user: ans
ansible_ssh_private_key_file: /home/vagrant/.ssh/id_ed25519

### Подавление запроса fingeprint
ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

## Monitoring
promtail_download_url: https://github.com/grafana/loki/releases/download/v3.0.0/promtail-linux-amd64.zip
grafanadb: /vagrant/ansible/files/grafana.db.zip

## Front
nc_url: nc.local
front_nginx_config_file: /etc/nginx/sites-available/nc.local
ssl_certificate: /vagrant/ansible/key/certificate.crt
ssl_certificate_key: /vagrant/ansible/key/private.key

## App
# remote_archive_path: /vagrant/ansible/nextcloud_files.bz2
nc_data_files: /data
# Web servers access to db              
db_nc_access_hosts:     
  - 192.168.10.21
  - 192.168.10.22
#  - 192.168.10.50

## Databases
nc_database: nextcloud
mysql_nextcloud_user: ncuser
mysql_nextcloud_user_pass: ncuser
mysql_dump_file: /vagrant/ansible/files/nextcloud.sql
#mysql_dump_file_rep: /vagrant/ansible/files/nextcloud_replicate.sql  # Alternative

## Replication db
db_debug: true                        # Debug true|false
dbuser_replicator: replicator
dbuser_replicator_pass: replicator
master_host: 192.168.10.31            # Master: только один!
replication_host:                     # Slave: может быть несколько
  - 192.168.10.32
#  - 192.168.10.50

## Backup
dump_dir: /vagrant/ansible/files      # Директория для дампов
# Расписание в формате CRON
backup_state: absent                  # State: present or absent
weekday: "*"
hour: "*"
minute: "*/15"

# For debug
db_admin: root
db_admin_pass: root
db_admin_access_hosts:
  - 127.0.0.1       # localhost
  - 192.168.10.99   # Ansible
  - 192.168.10.1    # Main host (for debug)
