MACHINES = {
  :ansible => {
    :box_name => "generic/ubuntu2204",
    :vm_name => "router1",
    :net => [
              {ip: '192.168.50.250', adapter: 5, netmask: "255.255.255.0", virtualbox__intnet: "ansible-net"},
            ]
},
  :router1 => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "router1",
        :net => [
                   {ip: '10.0.10.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r1-r2"},
                   {ip: '10.0.12.1', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r1-r3"},
                   {ip: '192.168.10.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "net1"},
                   {ip: '192.168.50.10', adapter: 5, netmask: "255.255.255.0", virtualbox__intnet: "ansible-net"},
                ]
  },

  :router2 => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "router2",
        :net => [
                   {ip: '10.0.10.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r1-r2"},
                   {ip: '10.0.11.2', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r2-r3"},
                   {ip: '192.168.20.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "net2"},
                   {ip: '192.168.50.11', adapter: 5, netmask: "255.255.255.0", virtualbox__intnet: "ansible-net"},
                ]
  },

  :router3 => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "router3",
        :net => [
                   {ip: '10.0.11.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r2-r3"},
                   {ip: '10.0.12.2', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r1-r3"},
                   {ip: '192.168.30.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "net3"},
                   {ip: '192.168.50.12', adapter: 5, netmask: "255.255.255.0", virtualbox__intnet: "ansible-net"},
                ]
  }

}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|
  
      config.vm.define boxname do |box|
  
          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
  
          boxconfig[:net].each do |ipconf|
            box.vm.network "private_network", ip: ipconf[:ip], adapter: ipconf[:adapter], netmask: ipconf[:netmask], virtualbox__intnet: ipconf[:virtualbox__intnet]
          end
                    
          case boxname.to_s

          when "router1"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
                systemctl restart sshd.service
              SHELL

          when "router2"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
            systemctl restart sshd.service
              SHELL

          when "router3"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
                systemctl restart sshd.service  
              SHELL

          when "ansible"
            box.vm.synced_folder "g:\\OTUS\\dz21\\", "/vagrant", disabled: false
            #config.vm.synced_folder ".", "/vagrant"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
                systemctl restart sshd.service
            sudo apt-get update -y &&                            
            sudo apt-get install python3 -y &&
            sudo apt-get install ansible -y &&
            sudo apt-get install nano -y
              SHELL
          end
  
        end
  
    end
    
end 
