---
# tasks file for roles/db

    - name: Обновление списка пакетов
      apt:
        update_cache: yes

    - name: Установка MySQL
      apt:
        name: mysql-server
        state: present

    - name: Запуск сервиса MySQL
      service:
        name: mysql
        state: started
        enabled: yes

    - name: update mysql root password for all root accounts
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ ansible_fqdn }}"
        - 127.0.0.1
        - ::1
        - localhost


    - name: Создание базы данных и пользователя
      mysql_db:
        name: mydatabase
        state: present
      tags: debug

    - name: Создание пользователя и предоставление прав
      mysql_user:
        name: myuser
        password: mypassword
        priv: 'mydatabase.*:ALL'
        state: present