---
# tasks file for roles/db

    - name: Обновление списка пакетов
      apt:
        update_cache: yes

    - name: Установка MySQL
      apt:
        name: mysql-server
        state: present        

    - name: Установка MySQL
      apt:
        name: mysql-server
        state: present

    - name: Запуск сервиса MySQL
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL root password
      shell: mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"
      tags:
        - debug

    - name: create a new database
      mysql_db:
        name: testdb
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_host: localhost
        login_port: 3306

    # - name: add sample data to database
    #   copy:
    #     src: dump.sql
    #     dest: /tmp/dump.sql

    # - name: insert sample data into database
    #   mysql_db:
    #     name: testdb
    #     state: import
    #     target: /tmp/dump.sql
    #     login_user: root
    #     login_password: "{{ mysql_root_password }}"