- name: Create MySQL User for Nextcloud
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ mysql_nextcloud_user }}"
    host: localhost
    password: "{{ mysql_nextcloud_pass }}"
    state: present

- name: Create Nextcloud Database
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: nextcloud
    state: present
    collation: utf8mb4_general_ci
    encoding: utf8mb4  

- name: Grant Privileges to MySQL User on Nextcloud Database
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ mysql_nextcloud_user }}"
    host: "{{ ','.join(app_ip) }}"
    priv: 'nextcloud.*:ALL'
    state: present

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False        
  
- name: Copy config
  template:
    src: 50-server.cnf
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf 

- name: Initialize mariadb
  service:
    name: mariadb
    state: restarted

- name: Import MySQL dump nextcloud
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    # login_user: "{{ mysql_nextcloud_user }}"
    # login_password: "{{ mysql_nextcloud_pass }}"
    db: nextcloud
    state: import
    target: "{{ mysql_dump_file }}"
