- name: Update apt's repositories
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: Install required packages
  apt:
     name:
       - docker.io
       - python3-pip
     state: present

- name: Install docker-py
  pip:
    name: docker-py

- name: Pull ONLYOFFICE Docker images
  docker_image:
    name: onlyoffice/documentserver
    state: present

- name: Create a network for ONLYOFFICE
  docker_network:
    name: onlyoffice_network
    state: present

- name: Run ONLYOFFICE Document Server container
  community.docker.docker_container:
    name: onlyoffice
    image: onlyoffice/documentserver
    state: started
    restart_policy: always
    networks:
      - name: onlyoffice_network
    ports:
      - "{{ onlyoffice_ext_port }}:80"
