- name: Update apt's repositories
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: Install packages
  apt:
    name:
      - libaio1
      - python3-pip
      - mariadb-server
    state: present

- name: Make sure mysql module is installed
  pip:
    name: pymysql

  # mysql_secure_installation
- name: Delete Hostname based MySQL user
  mysql_user: 
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: root 
    host: "{{ansible_nodename}}" 
    state: absent

  # mysql_secure_installation
- name: Remove MySQL test database
  mysql_db: login_unix_socket=/var/run/mysqld/mysqld.sock name=test state=absent

# - name: Выполнение SQL-запроса для удаления записей c пользователем nextcloud ####### 🔆
#   community.mysql.mysql_query:
#         login_unix_socket: /var/run/mysqld/mysqld.sock
#         login_user: root
#         login_host: localhost
#         query: "DELETE FROM mysql.user WHERE User='nextcloud';"  
#   tags:
#      - xxx

# - name: Reload privilege tables
#   command: 'mysql -ne "{{ item }}"'
#   with_items:
#     - FLUSH PRIVILEGES
#   changed_when: False      

- name: Create MySQL User for NextCloud  ### ❌❌❌
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ mysql_nextcloud_user }}"
    host: localhost
    password: "{{ mysql_nextcloud_password }}"
    state: present

- name: Create Nextcloud Database
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: nextcloud
    state: present
    collation: utf8mb4_general_ci
    encoding: utf8mb4  

- name: Grant Privileges to MySQL User on Nextcloud Database
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    #login_user: root
    name: "{{ mysql_nextcloud_user }}"
    #password: "{{ mysql_nextcloud_password }}"
  #  host: "{{ item }}"
    host: "192.168.10.21"
    priv: 'nextcloud.*:ALL'
    state: present
  # with_items:
  #       - "192.168.10.21"
  #       - "192.168.10.22"
      

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False        
  

- name: Copy config
  template:
    src: 50-server.conf
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf

# - name: Run new galera cluster
#   command: galera_new_cluster

- name: Initialize mariadb
  service:
    name: mariadb
    state: restarted
