---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      addresses:
      - 192.168.255.2/29
      routes:
      - to: default
        via: 192.168.255.1
    eth2:
      addresses:
      -  192.168.255.9/30
    eth3:
      addresses:
      - 192.168.50.11/24 