---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      addresses:
      - 192.168.255.1/29
      routes:
      - to: 192.168.0.0/28
        via: 192.168.255.3
      - to: 192.168.255.10/30
        via: 192.168.255.2

    eth2:
      addresses:
      - 192.168.50.10/24 